/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'itc' : null } |
  { 'filing' : null } |
  { 'gstBasics' : null };
export type Plan = { 'premium' : null } |
  { 'free' : null };
export type Role = { 'admin' : null } |
  { 'user' : null };
export type Slab = { 'slab12' : null } |
  { 'slab18' : null } |
  { 'slab28' : null } |
  { 'slab5' : null };
export type Status = { 'closed' : null } |
  { 'assigned' : null } |
  { 'pending' : null };
export interface T {
  'status' : Status,
  'userEmail' : string,
  'queryDescription' : string,
  'name' : string,
  'createdDate' : bigint,
  'fileUpload' : [] | [string],
  'phone' : string,
}
export interface T__1 {
  'subscriptionExpiry' : [] | [bigint],
  'name' : string,
  'plan' : Plan,
  'role' : Role,
  'businessName' : [] | [string],
  'email' : string,
  'gstin' : [] | [string],
}
export interface T__2 {
  'customerName' : string,
  'status' : string,
  'itemTotal' : number,
  'userEmail' : string,
  'pdfLink' : [] | [string],
  'customerPhone' : string,
  'createdDate' : bigint,
  'gstAmount' : number,
  'grandTotal' : number,
  'invoiceNumber' : string,
  'itemName' : string,
  'quantity' : bigint,
  'gstSlab' : Slab,
  'price' : number,
}
export interface T__3 {
  'title' : string,
  'userEmail' : [] | [string],
  'dueDateType' : Type,
  'notificationDate' : [] | [bigint],
  'reminderEnabled' : boolean,
  'dueDate' : bigint,
  'description' : string,
}
export interface T__4 {
  'title' : string,
  'fullContent' : string,
  'isPremiumOnly' : boolean,
  'shortDescription' : string,
}
export interface T__5 {
  'displayOrder' : bigint,
  'explanation' : [] | [string],
  'correctAnswer' : [] | [string],
  'quizQuestion' : [] | [string],
  'description' : string,
  'category' : Category,
  'topicTitle' : string,
}
export interface T__6 {
  'isSaved' : boolean,
  'userEmail' : string,
  'cgst' : number,
  'sgst' : number,
  'gstAmount' : number,
  'totalAmount' : number,
  'timestamp' : bigint,
  'baseAmount' : number,
  'gstSlab' : Slab,
  'isInclusive' : boolean,
}
export type Type = { 'gstFiling' : null } |
  { 'custom' : null } |
  { 'advanceTax' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomReminder' : ActorMethod<[string, string, bigint, boolean], T__3>,
  'createGstCalculation' : ActorMethod<[string, number, Slab, boolean], T__6>,
  'createInvoice' : ActorMethod<
    [string, string, string, string, bigint, number, Slab],
    [] | [T__2]
  >,
  'deleteCalculation' : ActorMethod<[string, bigint], boolean>,
  'deleteInvoice' : ActorMethod<[string], boolean>,
  'getAllCaLeads' : ActorMethod<[], Array<T>>,
  'getAllLearningContent' : ActorMethod<[], Array<T__5>>,
  'getCalculationsByUser' : ActorMethod<[string], Array<T__6>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [T__1]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLearningContentByCategory' : ActorMethod<[Category], Array<T__5>>,
  'getTaxTips' : ActorMethod<[], Array<T__4>>,
  'getUpcomingDueDates' : ActorMethod<[], Array<T__3>>,
  'getUserCaLeads' : ActorMethod<[], Array<T>>,
  'getUserCustomReminders' : ActorMethod<[], Array<T__3>>,
  'getUserInvoices' : ActorMethod<[string], Array<T__2>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [T__1]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'preloadLearningContent' : ActorMethod<[], undefined>,
  'preloadStatutoryDueDates' : ActorMethod<[], undefined>,
  'preloadTaxTips' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[T__1], undefined>,
  'submitCaLead' : ActorMethod<[string, string, string, [] | [string]], T>,
  'updateCaLeadStatus' : ActorMethod<[string, Status], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];