/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'gstFiling' : IDL.Null,
  'custom' : IDL.Null,
  'advanceTax' : IDL.Null,
});
export const T__3 = IDL.Record({
  'title' : IDL.Text,
  'userEmail' : IDL.Opt(IDL.Text),
  'dueDateType' : Type,
  'notificationDate' : IDL.Opt(IDL.Int),
  'reminderEnabled' : IDL.Bool,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
});
export const Slab = IDL.Variant({
  'slab12' : IDL.Null,
  'slab18' : IDL.Null,
  'slab28' : IDL.Null,
  'slab5' : IDL.Null,
});
export const T__6 = IDL.Record({
  'isSaved' : IDL.Bool,
  'userEmail' : IDL.Text,
  'cgst' : IDL.Float64,
  'sgst' : IDL.Float64,
  'gstAmount' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'baseAmount' : IDL.Float64,
  'gstSlab' : Slab,
  'isInclusive' : IDL.Bool,
});
export const T__2 = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'itemTotal' : IDL.Float64,
  'userEmail' : IDL.Text,
  'pdfLink' : IDL.Opt(IDL.Text),
  'customerPhone' : IDL.Text,
  'createdDate' : IDL.Int,
  'gstAmount' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'invoiceNumber' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'gstSlab' : Slab,
  'price' : IDL.Float64,
});
export const Status = IDL.Variant({
  'closed' : IDL.Null,
  'assigned' : IDL.Null,
  'pending' : IDL.Null,
});
export const T = IDL.Record({
  'status' : Status,
  'userEmail' : IDL.Text,
  'queryDescription' : IDL.Text,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'fileUpload' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const Category = IDL.Variant({
  'itc' : IDL.Null,
  'filing' : IDL.Null,
  'gstBasics' : IDL.Null,
});
export const T__5 = IDL.Record({
  'displayOrder' : IDL.Nat,
  'explanation' : IDL.Opt(IDL.Text),
  'correctAnswer' : IDL.Opt(IDL.Text),
  'quizQuestion' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : Category,
  'topicTitle' : IDL.Text,
});
export const Plan = IDL.Variant({ 'premium' : IDL.Null, 'free' : IDL.Null });
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const T__1 = IDL.Record({
  'subscriptionExpiry' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'plan' : Plan,
  'role' : Role,
  'businessName' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'gstin' : IDL.Opt(IDL.Text),
});
export const T__4 = IDL.Record({
  'title' : IDL.Text,
  'fullContent' : IDL.Text,
  'isPremiumOnly' : IDL.Bool,
  'shortDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
      [T__3],
      [],
    ),
  'createGstCalculation' : IDL.Func(
      [IDL.Text, IDL.Float64, Slab, IDL.Bool],
      [T__6],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, Slab],
      [IDL.Opt(T__2)],
      [],
    ),
  'deleteCalculation' : IDL.Func([IDL.Text, IDL.Int], [IDL.Bool], []),
  'deleteInvoice' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllCaLeads' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getAllLearningContent' : IDL.Func([], [IDL.Vec(T__5)], ['query']),
  'getCalculationsByUser' : IDL.Func([IDL.Text], [IDL.Vec(T__6)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T__1)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLearningContentByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(T__5)],
      ['query'],
    ),
  'getTaxTips' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
  'getUpcomingDueDates' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getUserCaLeads' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getUserCustomReminders' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getUserInvoices' : IDL.Func([IDL.Text], [IDL.Vec(T__2)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__1)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'preloadLearningContent' : IDL.Func([], [], []),
  'preloadStatutoryDueDates' : IDL.Func([], [], []),
  'preloadTaxTips' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([T__1], [], []),
  'submitCaLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [T],
      [],
    ),
  'updateCaLeadStatus' : IDL.Func([IDL.Text, Status], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'gstFiling' : IDL.Null,
    'custom' : IDL.Null,
    'advanceTax' : IDL.Null,
  });
  const T__3 = IDL.Record({
    'title' : IDL.Text,
    'userEmail' : IDL.Opt(IDL.Text),
    'dueDateType' : Type,
    'notificationDate' : IDL.Opt(IDL.Int),
    'reminderEnabled' : IDL.Bool,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
  });
  const Slab = IDL.Variant({
    'slab12' : IDL.Null,
    'slab18' : IDL.Null,
    'slab28' : IDL.Null,
    'slab5' : IDL.Null,
  });
  const T__6 = IDL.Record({
    'isSaved' : IDL.Bool,
    'userEmail' : IDL.Text,
    'cgst' : IDL.Float64,
    'sgst' : IDL.Float64,
    'gstAmount' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'baseAmount' : IDL.Float64,
    'gstSlab' : Slab,
    'isInclusive' : IDL.Bool,
  });
  const T__2 = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'itemTotal' : IDL.Float64,
    'userEmail' : IDL.Text,
    'pdfLink' : IDL.Opt(IDL.Text),
    'customerPhone' : IDL.Text,
    'createdDate' : IDL.Int,
    'gstAmount' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'invoiceNumber' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'gstSlab' : Slab,
    'price' : IDL.Float64,
  });
  const Status = IDL.Variant({
    'closed' : IDL.Null,
    'assigned' : IDL.Null,
    'pending' : IDL.Null,
  });
  const T = IDL.Record({
    'status' : Status,
    'userEmail' : IDL.Text,
    'queryDescription' : IDL.Text,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'fileUpload' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const Category = IDL.Variant({
    'itc' : IDL.Null,
    'filing' : IDL.Null,
    'gstBasics' : IDL.Null,
  });
  const T__5 = IDL.Record({
    'displayOrder' : IDL.Nat,
    'explanation' : IDL.Opt(IDL.Text),
    'correctAnswer' : IDL.Opt(IDL.Text),
    'quizQuestion' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : Category,
    'topicTitle' : IDL.Text,
  });
  const Plan = IDL.Variant({ 'premium' : IDL.Null, 'free' : IDL.Null });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const T__1 = IDL.Record({
    'subscriptionExpiry' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'plan' : Plan,
    'role' : Role,
    'businessName' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'gstin' : IDL.Opt(IDL.Text),
  });
  const T__4 = IDL.Record({
    'title' : IDL.Text,
    'fullContent' : IDL.Text,
    'isPremiumOnly' : IDL.Bool,
    'shortDescription' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
        [T__3],
        [],
      ),
    'createGstCalculation' : IDL.Func(
        [IDL.Text, IDL.Float64, Slab, IDL.Bool],
        [T__6],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, Slab],
        [IDL.Opt(T__2)],
        [],
      ),
    'deleteCalculation' : IDL.Func([IDL.Text, IDL.Int], [IDL.Bool], []),
    'deleteInvoice' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllCaLeads' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getAllLearningContent' : IDL.Func([], [IDL.Vec(T__5)], ['query']),
    'getCalculationsByUser' : IDL.Func([IDL.Text], [IDL.Vec(T__6)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T__1)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLearningContentByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(T__5)],
        ['query'],
      ),
    'getTaxTips' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
    'getUpcomingDueDates' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getUserCaLeads' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getUserCustomReminders' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getUserInvoices' : IDL.Func([IDL.Text], [IDL.Vec(T__2)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__1)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'preloadLearningContent' : IDL.Func([], [], []),
    'preloadStatutoryDueDates' : IDL.Func([], [], []),
    'preloadTaxTips' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([T__1], [], []),
    'submitCaLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [T],
        [],
      ),
    'updateCaLeadStatus' : IDL.Func([IDL.Text, Status], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };