/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface T__1 {
    subscriptionExpiry?: bigint;
    name: string;
    plan: Plan;
    role: Role;
    businessName?: string;
    email: string;
    gstin?: string;
}
export interface T__4 {
    title: string;
    fullContent: string;
    isPremiumOnly: boolean;
    shortDescription: string;
}
export interface T__3 {
    title: string;
    userEmail?: string;
    dueDateType: Type;
    notificationDate?: bigint;
    reminderEnabled: boolean;
    dueDate: bigint;
    description: string;
}
export interface T__2 {
    customerName: string;
    status: string;
    itemTotal: number;
    userEmail: string;
    pdfLink?: string;
    customerPhone: string;
    createdDate: bigint;
    gstAmount: number;
    grandTotal: number;
    invoiceNumber: string;
    itemName: string;
    quantity: bigint;
    gstSlab: Slab;
    price: number;
}
export interface T {
    status: Status;
    userEmail: string;
    queryDescription: string;
    name: string;
    createdDate: bigint;
    fileUpload?: string;
    phone: string;
}
export interface T__5 {
    displayOrder: bigint;
    explanation?: string;
    correctAnswer?: string;
    quizQuestion?: string;
    description: string;
    category: Category;
    topicTitle: string;
}
export interface T__6 {
    isSaved: boolean;
    userEmail: string;
    cgst: number;
    sgst: number;
    gstAmount: number;
    totalAmount: number;
    timestamp: bigint;
    baseAmount: number;
    gstSlab: Slab;
    isInclusive: boolean;
}
export enum Category {
    itc = "itc",
    filing = "filing",
    gstBasics = "gstBasics"
}
export enum Plan {
    premium = "premium",
    free = "free"
}
export enum Role {
    admin = "admin",
    user = "user"
}
export enum Slab {
    slab12 = "slab12",
    slab18 = "slab18",
    slab28 = "slab28",
    slab5 = "slab5"
}
export enum Status {
    closed = "closed",
    assigned = "assigned",
    pending = "pending"
}
export enum Type {
    gstFiling = "gstFiling",
    custom = "custom",
    advanceTax = "advanceTax"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomReminder(title: string, description: string, dueDate: bigint, reminderEnabled: boolean): Promise<T__3>;
    createGstCalculation(userEmail: string, baseAmount: number, gstSlab: Slab, isInclusive: boolean): Promise<T__6>;
    createInvoice(userEmail: string, customerName: string, customerPhone: string, itemName: string, quantity: bigint, price: number, gstSlab: Slab): Promise<T__2 | null>;
    deleteCalculation(userEmail: string, timestamp: bigint): Promise<boolean>;
    deleteInvoice(invoiceNumber: string): Promise<boolean>;
    getAllCaLeads(): Promise<Array<T>>;
    getAllLearningContent(): Promise<Array<T__5>>;
    getCalculationsByUser(userEmail: string): Promise<Array<T__6>>;
    getCallerUserProfile(): Promise<T__1 | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLearningContentByCategory(category: Category): Promise<Array<T__5>>;
    getTaxTips(): Promise<Array<T__4>>;
    getUpcomingDueDates(): Promise<Array<T__3>>;
    getUserCaLeads(): Promise<Array<T>>;
    getUserCustomReminders(): Promise<Array<T__3>>;
    getUserInvoices(userEmail: string): Promise<Array<T__2>>;
    getUserProfile(user: Principal): Promise<T__1 | null>;
    isCallerAdmin(): Promise<boolean>;
    preloadLearningContent(): Promise<void>;
    preloadStatutoryDueDates(): Promise<void>;
    preloadTaxTips(): Promise<void>;
    saveCallerUserProfile(profile: T__1): Promise<void>;
    submitCaLead(name: string, phone: string, queryDescription: string, fileUpload: string | null): Promise<T>;
    updateCaLeadStatus(leadKey: string, newStatus: Status): Promise<boolean>;
}
import type { Category as _Category, Plan as _Plan, Role as _Role, Slab as _Slab, Status as _Status, T as _T, T__1 as _T__1, T__2 as _T__2, T__3 as _T__3, T__5 as _T__5, T__6 as _T__6, Type as _Type, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomReminder(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<T__3> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomReminder(arg0, arg1, arg2, arg3);
                return from_candid_T__3_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomReminder(arg0, arg1, arg2, arg3);
            return from_candid_T__3_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGstCalculation(arg0: string, arg1: number, arg2: Slab, arg3: boolean): Promise<T__6> {
        if (this.processError) {
            try {
                const result = await this.actor.createGstCalculation(arg0, arg1, to_candid_Slab_n9(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_T__6_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGstCalculation(arg0, arg1, to_candid_Slab_n9(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_T__6_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: number, arg6: Slab): Promise<T__2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Slab_n9(this._uploadFile, this._downloadFile, arg6));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Slab_n9(this._uploadFile, this._downloadFile, arg6));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCalculation(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalculation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalculation(arg0, arg1);
            return result;
        }
    }
    async deleteInvoice(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async getAllCaLeads(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCaLeads();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCaLeads();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLearningContent(): Promise<Array<T__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLearningContent();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLearningContent();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCalculationsByUser(arg0: string): Promise<Array<T__6>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalculationsByUser(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalculationsByUser(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<T__1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLearningContentByCategory(arg0: Category): Promise<Array<T__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLearningContentByCategory(to_candid_Category_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLearningContentByCategory(to_candid_Category_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaxTips(): Promise<Array<T__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxTips();
            return result;
        }
    }
    async getUpcomingDueDates(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingDueDates();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingDueDates();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCaLeads(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCaLeads();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCaLeads();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCustomReminders(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCustomReminders();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCustomReminders();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserInvoices(arg0: string): Promise<Array<T__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInvoices(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInvoices(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<T__1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async preloadLearningContent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.preloadLearningContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.preloadLearningContent();
            return result;
        }
    }
    async preloadStatutoryDueDates(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.preloadStatutoryDueDates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.preloadStatutoryDueDates();
            return result;
        }
    }
    async preloadTaxTips(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.preloadTaxTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.preloadTaxTips();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: T__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_T__1_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_T__1_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitCaLead(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCaLead(arg0, arg1, arg2, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3));
                return from_candid_T_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCaLead(arg0, arg1, arg2, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3));
            return from_candid_T_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCaLeadStatus(arg0: string, arg1: Status): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaLeadStatus(arg0, to_candid_Status_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaLeadStatus(arg0, to_candid_Status_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Plan_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plan): Plan {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Slab_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Slab): Slab {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_T__1_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_T__2_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__2): T__2 {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_T__3_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__3): T__3 {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_T__5_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__5): T__5 {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_T__6_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__6): T__6 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_T_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__2]): T__2 | null {
    return value.length === 0 ? null : from_candid_T__2_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__1]): T__1 | null {
    return value.length === 0 ? null : from_candid_T__1_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isSaved: boolean;
    userEmail: string;
    cgst: number;
    sgst: number;
    gstAmount: number;
    totalAmount: number;
    timestamp: bigint;
    baseAmount: number;
    gstSlab: _Slab;
    isInclusive: boolean;
}): {
    isSaved: boolean;
    userEmail: string;
    cgst: number;
    sgst: number;
    gstAmount: number;
    totalAmount: number;
    timestamp: bigint;
    baseAmount: number;
    gstSlab: Slab;
    isInclusive: boolean;
} {
    return {
        isSaved: value.isSaved,
        userEmail: value.userEmail,
        cgst: value.cgst,
        sgst: value.sgst,
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        baseAmount: value.baseAmount,
        gstSlab: from_candid_Slab_n13(_uploadFile, _downloadFile, value.gstSlab),
        isInclusive: value.isInclusive
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: string;
    itemTotal: number;
    userEmail: string;
    pdfLink: [] | [string];
    customerPhone: string;
    createdDate: bigint;
    gstAmount: number;
    grandTotal: number;
    invoiceNumber: string;
    itemName: string;
    quantity: bigint;
    gstSlab: _Slab;
    price: number;
}): {
    customerName: string;
    status: string;
    itemTotal: number;
    userEmail: string;
    pdfLink?: string;
    customerPhone: string;
    createdDate: bigint;
    gstAmount: number;
    grandTotal: number;
    invoiceNumber: string;
    itemName: string;
    quantity: bigint;
    gstSlab: Slab;
    price: number;
} {
    return {
        customerName: value.customerName,
        status: value.status,
        itemTotal: value.itemTotal,
        userEmail: value.userEmail,
        pdfLink: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pdfLink)),
        customerPhone: value.customerPhone,
        createdDate: value.createdDate,
        gstAmount: value.gstAmount,
        grandTotal: value.grandTotal,
        invoiceNumber: value.invoiceNumber,
        itemName: value.itemName,
        quantity: value.quantity,
        gstSlab: from_candid_Slab_n13(_uploadFile, _downloadFile, value.gstSlab),
        price: value.price
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    userEmail: string;
    queryDescription: string;
    name: string;
    createdDate: bigint;
    fileUpload: [] | [string];
    phone: string;
}): {
    status: Status;
    userEmail: string;
    queryDescription: string;
    name: string;
    createdDate: bigint;
    fileUpload?: string;
    phone: string;
} {
    return {
        status: from_candid_Status_n21(_uploadFile, _downloadFile, value.status),
        userEmail: value.userEmail,
        queryDescription: value.queryDescription,
        name: value.name,
        createdDate: value.createdDate,
        fileUpload: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.fileUpload)),
        phone: value.phone
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayOrder: bigint;
    explanation: [] | [string];
    correctAnswer: [] | [string];
    quizQuestion: [] | [string];
    description: string;
    category: _Category;
    topicTitle: string;
}): {
    displayOrder: bigint;
    explanation?: string;
    correctAnswer?: string;
    quizQuestion?: string;
    description: string;
    category: Category;
    topicTitle: string;
} {
    return {
        displayOrder: value.displayOrder,
        explanation: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.explanation)),
        correctAnswer: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.correctAnswer)),
        quizQuestion: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.quizQuestion)),
        description: value.description,
        category: from_candid_Category_n26(_uploadFile, _downloadFile, value.category),
        topicTitle: value.topicTitle
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscriptionExpiry: [] | [bigint];
    name: string;
    plan: _Plan;
    role: _Role;
    businessName: [] | [string];
    email: string;
    gstin: [] | [string];
}): {
    subscriptionExpiry?: bigint;
    name: string;
    plan: Plan;
    role: Role;
    businessName?: string;
    email: string;
    gstin?: string;
} {
    return {
        subscriptionExpiry: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.subscriptionExpiry)),
        name: value.name,
        plan: from_candid_Plan_n32(_uploadFile, _downloadFile, value.plan),
        role: from_candid_Role_n34(_uploadFile, _downloadFile, value.role),
        businessName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.businessName)),
        email: value.email,
        gstin: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.gstin))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    userEmail: [] | [string];
    dueDateType: _Type;
    notificationDate: [] | [bigint];
    reminderEnabled: boolean;
    dueDate: bigint;
    description: string;
}): {
    title: string;
    userEmail?: string;
    dueDateType: Type;
    notificationDate?: bigint;
    reminderEnabled: boolean;
    dueDate: bigint;
    description: string;
} {
    return {
        title: value.title,
        userEmail: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.userEmail)),
        dueDateType: from_candid_Type_n6(_uploadFile, _downloadFile, value.dueDateType),
        notificationDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.notificationDate)),
        reminderEnabled: value.reminderEnabled,
        dueDate: value.dueDate,
        description: value.description
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    slab12: null;
} | {
    slab18: null;
} | {
    slab28: null;
} | {
    slab5: null;
}): Slab {
    return "slab12" in value ? Slab.slab12 : "slab18" in value ? Slab.slab18 : "slab28" in value ? Slab.slab28 : "slab5" in value ? Slab.slab5 : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    assigned: null;
} | {
    pending: null;
}): Status {
    return "closed" in value ? Status.closed : "assigned" in value ? Status.assigned : "pending" in value ? Status.pending : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itc: null;
} | {
    filing: null;
} | {
    gstBasics: null;
}): Category {
    return "itc" in value ? Category.itc : "filing" in value ? Category.filing : "gstBasics" in value ? Category.gstBasics : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): Plan {
    return "premium" in value ? Plan.premium : "free" in value ? Plan.free : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstFiling: null;
} | {
    custom: null;
} | {
    advanceTax: null;
}): Type {
    return "gstFiling" in value ? Type.gstFiling : "custom" in value ? Type.custom : "advanceTax" in value ? Type.advanceTax : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__5>): Array<T__5> {
    return value.map((x)=>from_candid_T__5_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__6>): Array<T__6> {
    return value.map((x)=>from_candid_T__6_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__3>): Array<T__3> {
    return value.map((x)=>from_candid_T__3_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__2>): Array<T__2> {
    return value.map((x)=>from_candid_T__2_n16(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Plan_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): _Plan {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_Slab_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Slab): _Slab {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_T__1_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): _T__1 {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscriptionExpiry?: bigint;
    name: string;
    plan: Plan;
    role: Role;
    businessName?: string;
    email: string;
    gstin?: string;
}): {
    subscriptionExpiry: [] | [bigint];
    name: string;
    plan: _Plan;
    role: _Role;
    businessName: [] | [string];
    email: string;
    gstin: [] | [string];
} {
    return {
        subscriptionExpiry: value.subscriptionExpiry ? candid_some(value.subscriptionExpiry) : candid_none(),
        name: value.name,
        plan: to_candid_Plan_n44(_uploadFile, _downloadFile, value.plan),
        role: to_candid_Role_n46(_uploadFile, _downloadFile, value.role),
        businessName: value.businessName ? candid_some(value.businessName) : candid_none(),
        email: value.email,
        gstin: value.gstin ? candid_some(value.gstin) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Slab): {
    slab12: null;
} | {
    slab18: null;
} | {
    slab28: null;
} | {
    slab5: null;
} {
    return value == Slab.slab12 ? {
        slab12: null
    } : value == Slab.slab18 ? {
        slab18: null
    } : value == Slab.slab28 ? {
        slab28: null
    } : value == Slab.slab5 ? {
        slab5: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    itc: null;
} | {
    filing: null;
} | {
    gstBasics: null;
} {
    return value == Category.itc ? {
        itc: null
    } : value == Category.filing ? {
        filing: null
    } : value == Category.gstBasics ? {
        gstBasics: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): {
    premium: null;
} | {
    free: null;
} {
    return value == Plan.premium ? {
        premium: null
    } : value == Plan.free ? {
        free: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    user: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    closed: null;
} | {
    assigned: null;
} | {
    pending: null;
} {
    return value == Status.closed ? {
        closed: null
    } : value == Status.assigned ? {
        assigned: null
    } : value == Status.pending ? {
        pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
